- name: Tests
  hosts: localhost
  connection: local
  vars:
    custom_resource: "{{ lookup('template', cr_file_path) | from_yaml }}"
  tasks:
  - import_tasks: ../common/tasks.yml
  - import_tasks: ../asserts/configmap_asserts.yml
  - import_tasks: ../common/wait_for_kiali_running.yml
  - import_tasks: ../asserts/pod_asserts.yml
