apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  version: "${KIALI_CR_SPEC_VERSION}"
  auth:
    strategy: $AUTH_STRATEGY
  deployment:
    accessible_namespaces: [ "${ACCESSIBLE_NAMESPACES}" ]
    image_name: $KIALI_IMAGE_NAME
    image_pull_policy: $KIALI_IMAGE_PULL_POLICY
    image_version: $KIALI_IMAGE_VERSION
    namespace: $NAMESPACE
    service_type: $SERVICE_TYPE
    verbose_mode: $VERBOSE_MODE
