apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: $AUTH_STRATEGY
  deployment:
    image_version: $IMAGE_VERSION
    namespace: $NAMESPACE
    verbose_mode: $VERBOSE_MODE
