language: go

go:
- 1.14

notifications:
  irc:
    channels:
      - chat.freenode.net#kiali
    on_success: change
    on_failure: change

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/

env:
  global:
  - secure: "qy2ptBm0rm1gu2tWGRYZVB+IGy2aJXz40lrTbh/v01kE/iauK7knUYlpY4hkHBR8tTuvmDipHJJZSPhQrGLiLJU7+lSlr4X2pBJbou+hGal0pPlio379Bn3UZ0RTPE1kw8E6e007gGEcTQmFDeOCxQ1Rtm426guaL4SnXBM5D3dtQqEVhkgYGjivnOl2wrrqz1gBF/76OUfCN4nTwhJqiyiM/ELX3hYQ7CZcRQ7sZ+RqXEpR6zum+tgGauQ7zO+ebWKGn76ZaInZ4hnTx/hoiBmQ5jm6vOpOK2+Vqrskleh8QUvSRk1p1qjjUDj0gqgX2NoxqTrqSb6kMjez3hJCCz8teibuDBNqmER/mSoTFZQhMZYKwnUSe+xM9O+O2gOgNTwdm0Ejj1cY28BH02YiondG0mrX+xplFyzsDXOPdUdQdkT2YNfy29LI7fd2knWT294TPmbrYeoRqb4sQ76d+8RSJlgFpjkR8ejJT/aW3mzwO76YdJQXhuYM9JZx14whMIxWHi0Pje3/PgV7RfceyxbFs9dSaaZ5GYv8dvEsiIkTFgpEVdP45eL8VXj/6ErapjU2YYB9qzTgb+rvTPqqyP3GN3U6nd9Kd768DZvrzT6jCoua/m3lWnBiLFZXofOB9SomqaWv81VcUSIvr2uDpVl+onFBBx3C3RZM70PV5Jg="
  - secure: "gYC5NDHZBMmTIPVzxXwZBFJ99UFnrnqN9YTNz3OxrN1qSrWi3g4nNhP2lyreKhaAg5IchYvHwjgktWYE25yCvsMLfaQQXw/2wCwRnEpcMDsVzZxVfExvy8bukhKlgKr8PXU+4mMTo1E+4b+HWdCTMQf0hKt6/7ccF8udY+VxXqQ6Kg9CrRSg3MtsMJR75rOUpJ2KgNG9N5GzCNl3hxwM+F7DpHEp0YstpAWqlugTHhsKGXEUfu/DGhRWfEmQnj0u8ra3qkjsRlanLcWdCfHR4lqPVuRRkeIP3QQkgJe283xVgt6t1sIUdMOSvoSqi+T469WI+nuO9ssPBikViQSc1P2vOay1p3dIx8PKmIvRlDr+fT5d8FvTafWCDMHOrAEJ3drkbjuMo/E3OXNq3QS8aXlFc17raa+gxihSQNVV1weyifng9+IO5JRoi1B9unOwuAl71Xt34uMAjCWJ2tZS/w4c5IPUaSlaXO4ULEgn0YEjxFnrroxBexFkWlgnT8wrjOg3JUOSbNSB1X81IoSEYiDg+Ddt/zn8lS0fQwAMvsuAODdY5EnMbLFDUKOEZxMl6GVAvDzp0LxGfzFLlHTGkPBy92Ox/59qRLXVvUcCn++Dl9TvnI5g8mSTcWjmDDHyTSShzfO/y/+aMc2mQ/OEYZ7u5o8qHOgeqFjrzHN72P0="

# The project committed the vendor directory into source so there is no need for
# travis to install dep and pull down dependencies.
# Therefore, the dep-X targets are commented out here. Uncomment these if the project
# decided to no longer commit vendor dependencies into the source tree.
# See: https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory
install:
 - make swagger-install
 - make lint-install

script:
  - if [ ! -z "$(gofmt -l ${GO_FILES})" ]; then echo "These files need to be formatted:" "$(gofmt -l ${GO_FILES})";echo "Diff files:"; gofmt -d ${GO_FILES}; exit 1; fi # Gofmt Linter
  - make lint
  - make clean build test-race
  - make swagger-travis
