sudo: required

services:
- docker

language: go

go:
- 1.8.3

notifications:
  irc:
    channels:
    - chat.freenode.net#BOGUS_DOES_NOT_EXIST

env:
  global:
  - secure: "NxfAB5mYGZDzw9YS51eruUsLf9tLiiiVMcHIy/2CNhCNorMKXIjCAegGeHxo2iuZKmrJeLokMtFQ13gsCqOR5tKsYxG9D7trFO4nLh5nOJ2otrlE0/ggSFBq0jieh00fJYX/MJ76YYZlBvXdTwdmaaCNVFG+DDApRwErMvQF/TakrZlVpLi4M1hZtChELvCpNsKNDrcj1jkKIUSypIWPziSsGP7u7MD7Dbk5T5oHumaHuMfQ9R0gidaD040fFDVfhQ73So8VTVQCljO7Ut+eMyGLGQow5t6p8ntI3ZuznBXIBRHnwYIRyZy4Ygu5IjIKxtjhMXByFQ3TyUQAarKfNKE7ifU+Mz6CMpRVz/VkfTn6J53V8CDC0Kgh4L7hTikiCi39+pjAXWX69ci33ioYE/ey5gr40jgzehrq88hf7MZEUIGhuNMmdTvgl5m7fokimNXT6EISNhjt5IICt2SCamqjpyGqhKEE3yV2jGg6XCkmyT/vkvnm4B/Pznwerp9BWxruHF86DKAZ24+8JwvUP3UtMVglOnNIb/Bh7A+Gpj0mGQFbrd+mB/OB0lJ7HnLHOXf8tasApS/d1NOlCSFdKWj9ZCbpNn0optBOeKM/0pxx9tAWGyz1NEN0U0K9JmHiFb/FO2Eba2wQcmDhlV5AWKQ14v3nKnKQIRYQpWkjfgA="
  - secure: "Y3zLzPux/wqSMI1wy0j0OoSqhqk+6mLTk4OsHYm+d/6o/KTe84xfenRM7Z9FImWHujfShHZmIl9Y1lGwB8/4Xsi1Mli82m+krmB84lG4NHjK/btD3gE3+gI/0FdYDkbCMdHLR2u4Nz73WOkI34oML7oRxPCMrkyxaO66PT31fMA8iujaE4De7YIVYI6mosa6+16zpvtzxcl0+zjynnXSEgJa5E7opjCYPgPxItzUBEcKU5KuW9G1Yg4W3VRcwP8HSXjBX2h7wLFRsAVQ1IOADHjrMd+j501GiaqUK4uDFnYedBBv4ONoGK0eVxfKYmMNYskSvx7Ko4fCmaCj5/70ujGq1ZvaXZCOKnwIPVFs4bBcnDDRHVJ359CyT8qYq6Tp91EBFD7Qa7Vz0NFoKIiBraBVjztfYz6OMOYLWxF6++oTcl24ZrhZWEly7XxDcKwPShoaWSq79OTvSTmQOmABXRe5zi4f+sfZd3KkTL7ZNoeUSnfvrNKbCPnje0Egq1i9Xffmtiv8Bjqlei3gB6PR6gaAlOx0Lq8F2gf2A2Xlg27yKzElR6iC50T6d6X1DqFzUu8TeYL/c8kESHqXl85fUSRalp8jIu6Zk9jauzxqtuDLcOq0BAackKdQKNojn9RUjrYRNV1qNnh7mB2xBKPPNXRdIAJjet2Tag4wTFXo/1w="

# The project committed the vendor directory into source so there is no need for
# travis to install dep and pull down dependencies.
# Therefore, the dep-X targets are commmented out here. Uncomment these if the project
# decided to no longer commit vendor dependencies into the source tree.
# See: https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory
#install:
#- make dep-install
#- make dep-update

script: make test

# Push the docker images to docker hub
# If a tag build, use the tag as docker version; otherwise, use branch name as docker version (where master==latest)
after_success:
- export COMMIT_HASH=${TRAVIS_COMMIT}
- export DOCKER_VERSION=$(if [ "$TRAVIS_TAG" != "" ]; then echo $TRAVIS_TAG; elif [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
- export DOCKER_USER=$(if [ "$DOCKER_USER" == "" ]; then echo "unknown"; else echo $DOCKER_USER ; fi)
- export DOCKER_PASS=$(if [ "$DOCKER_PASS" == "" ]; then echo "unknown"; else echo $DOCKER_PASS ; fi)
- echo DOCKER_VERSION=$DOCKER_VERSION
- make build
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
- make docker
- docker push jmazzitelli/sws

# Build only the master branch (for "latest" release) and version tags (e.g. "1.2.3" or "1.1.2.RC2" or "2.1.5.Final")
# Add branch names below if we want to push docker images built off of those branches.
branches:
  only:
  - master
  - /^(\d+\.){2}(\d+){1}(\.[a-zA-Z\d]+)?$/
