- name: Tests
  hosts: localhost
  connection: local
  vars:
   kiali_operator_cr: "{{ lookup('template', kiali_operator_cr_file_path) | from_yaml }}"
  tasks:
  - import_tasks: 'tests/tasks.yml'
  # - import_tasks: ../asserts/accessible_namespaces_contains.yml
  #   vars:
  #     namespace_list: [ '**' ]
  # - import_tasks: '../asserts/configmap_asserts.yml'
  # - import_tasks: '../asserts/pod_asserts.yml'
  # - import_tasks: '../asserts/multi-tenancy/label_selector_asserts.yml'
  # - import_tasks: '../asserts/multi-tenancy/role_asserts.yml'
