apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-service-account
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
