- name: "Delete additional Kiali roles in accessible namespaces"
  ignore_errors: yes
  k8s:
    state: absent
    api_version: "{{ k8s_item.apiVersion }}"
    kind: "{{ k8s_item.kind }}"
    namespace: "{{ role_namespace }}"
    name: "{{ k8s_item.metadata.name }}"
  register: delete_result
  until: delete_result.result == {} or (delete_result.result.status is defined and delete_result.result.status == "Success")
  retries: 6
  delay: 10
  when:
  - is_openshift == True or is_k8s == True
  - role_namespace is defined
  - k8s_item is defined
  - k8s_item.apiVersion is defined
  - k8s_item.kind is defined
  - k8s_item.metadata is defined
  - k8s_item.metadata.name is defined
  with_items:
  - "{{ query('k8s', namespace=role_namespace, kind='RoleBinding', resource_name='kiali', api_version='rbac.authorization.k8s.io/v1') }}"
  - "{{ query('k8s', namespace=role_namespace, kind='Role', resource_name='kiali', api_version='rbac.authorization.k8s.io/v1') }}"
  - "{{ query('k8s', namespace=role_namespace, kind='Role', resource_name='kiali-viewer', api_version='rbac.authorization.k8s.io/v1') }}"
  loop_control:
    loop_var: k8s_item
