apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
redirectURIs:
  - {{ kiali_route_url }}
  - localhost:3000
grantMethod: auto
allowAnyScope: true
