apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kiali-cert-secret
    {{ kiali_vars.apidocs.annotations.api_spec_annotation_name }}: {{ '' if kiali_vars.server.web_root == '/' else kiali_vars.server.web_root }}/swagger.json
    {{ kiali_vars.apidocs.annotations.api_type_annotation_name }}: rest
spec:
{% if kiali_vars.deployment.service_type is defined %}
  type: {{ kiali_vars.deployment.service_type }}
{% endif %}
  ports:
  - name: {{ 'http' if kiali_vars.identity.cert_file == "" else 'tcp' }}
    protocol: TCP
    port: {{ kiali_vars.server.port }}
  selector:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  {% if kiali_vars.deployment.additional_service_yaml is defined %}{{ kiali_vars.deployment.additional_service_yaml | to_nice_yaml(indent=0) | trim | indent(2) }}{% endif %}
