apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  annotations:
    # For ingress-nginx versions older than 0.20.0
    # (see: https://github.com/kubernetes/ingress-nginx/issues/3416#issuecomment-438247948)
    nginx.ingress.kubernetes.io/secure-backends: "true"
    # For ingress-nginx versions 0.20.0 and later
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - path: {{ kiali_vars.server.web_root }}
        backend:
          serviceName: kiali
          servicePort: {{ kiali_vars.server.port }}
