default: {"image_name": "quay.io/kiali/kiali", "image_version": "operator_version"}
v1.0: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.0"}
v1.12: {"image_name": "quay.io/kiali/kiali", "image_version": "v1.12"}
