###################################################################
# run-kiali-config-template.yaml
#
# This is intended to be used as a template configuration file
# for the developer tool 'run-kiali.sh'.
#
# This file is not intended to be used by Kiali other than when
# launched locally via 'run-kiali.sh'.
#
# If you want to know what settings Kiali supports, please see
# the spec field in the example Kiali CR found here:
# https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
#
###################################################################

auth:
  strategy: "anonymous"

clustering:
  # run-kiali is, by definition, running outside of a cluster so you must ignore home cluster
  # when ignore_home_cluster=true, use run-kiali.sh -cn option if the context name != cluster name.
  ignore_local_cluster: true

deployment:
  cluster_wide_access: true

external_services:
  custom_dashboards:
    enabled: false

  grafana:
    enabled: true
    internal_url: "${GRAFANA_URL}"
    external_url: "${GRAFANA_URL}"

  istio:
    url_service_version: "${ISTIOD_URL}"

  prometheus:
    url: "${PROMETHEUS_URL}"

  tracing:
    enabled: true
    provider: "${TRACING_APP}"
    internal_url: "${TRACING_URL}"
    external_url: "${TRACING_URL}"
    use_grpc: false

login_token:
  signing_key: "notsecure"
