# The Compatible Version Matrix between upstream Istio and Kiali
- meshName: "Istio"
  versionRange:
    - meshVersion: "1.14"
      kialiMinimumVersion: "1.50.0"
      kialiMaximumVersion: ""
    - meshVersion: "1.13"
      kialiMinimumVersion: "1.45.1"
      kialiMaximumVersion: "1.49"
    - meshVersion: "1.12"
      kialiMinimumVersion: "1.42.0"
      kialiMaximumVersion: "1.44.0"
    - meshVersion: "1.11"
      kialiMinimumVersion: "1.38.1"
      kialiMaximumVersion: "1.41"
    - meshVersion: "1.10"
      kialiMinimumVersion: "1.34.1"
      kialiMaximumVersion: "1.37"
    - meshVersion: "1.9"
      kialiMinimumVersion: "1.29.1"
      kialiMaximumVersion: "1.33"
    - meshVersion: "1.8"
      kialiMinimumVersion: "1.26.0"
      kialiMaximumVersion: "1.28"
    - meshVersion: "1.7"
      kialiMinimumVersion: "1.22.1"
      kialiMaximumVersion: "1.25"
    - meshVersion: "1.6"
      kialiMinimumVersion: "1.18.1"
      kialiMaximumVersion: "1.21"
    - meshVersion: "1.5"
      kialiFixedVersion: 
      - "1.17"
    - meshVersion: "1.4"
      kialiFixedVersion: 
      - "1.17"
    - meshVersion: "1.3"
      kialiFixedVersion: 
      - "1.17"
    - meshVersion: "1.2"
      kialiFixedVersion: 
      - "1.17"
    - meshVersion: "1.1"
      kialiFixedVersion: 
      - "1.17"
    - meshVersion: "1.0"
      kialiFixedVersion: 
      - "1.17"

# The Compatible Version Matrix between OpenShift Service Mesh and Kiali (there is a 1-to-1 relationship between Kiali and OSSM versions)
- meshName: "OpenShift Service Mesh"
  versionRange: 
    - meshVersion: "2.2"
      kialiFixedVersion: 
      - "1.48"
    - meshVersion: "2.1"
      kialiFixedVersion: 
      - "1.36"
    - meshVersion: "2.0"
      kialiFixedVersion:
      - "1.24"
    - meshVersion: "1.1"
      kialiFixedVersion: 
      - "1.12"
