run:
  timeout: 5m
  tests: true
issues:
  exclude-files:
  - doc.go
  - ".*\\.pb\\.go$"
  exclude-dirs:
  - frontend
linters:
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/kiali/kiali
