# Defaults for all user-facing Kiali settings. These are documented in kiali_cr.yaml.
#
# Note that these are under the main dictionary group "kiali_defaults".
# The actual vars used by the role are found in the vars/ directory.
# These defaults (the dictionaries under "kiali_defaults") are merged into the vars such that the values
# below (e.g. deployment, server, etc.) are merged in rather than completely replaced by user-supplied values.
#
# If new groups are added to these defaults, you must remember to add the merge code to vars/main.yml.

kiali_defaults:
  installation_tag: ""
  istio_namespace: ""

  api:
    namespaces:
      exclude:
      - "istio-operator"
      - "kube.*"
      - "openshift.*"
      - "ibm.*"
      - "kiali-operator"
      #label_selector:

  apidocs:
    annotations:
      api_spec_annotation_name: "kiali.io/api-spec"
      api_type_annotation_name: "kiali.io/api-type"

  auth:
    ldap:
      ldap_base: ""
      ldap_bind_dn: ""
      ldap_group_filter: "(cn=%s)"
      ldap_host: ""
      ldap_insecure_skip_verify: false
      ldap_mail_id_key: "mail"
      ldap_member_of_key: "memberOf"
      ldap_port: 0
      ldap_role_filter: ""
      ldap_search_filter: "(&(name={USERID}))"
      ldap_use_ssl: false
      ldap_user_filter: "(cn=%s)"
      ldap_user_id_key: "cn"
    strategy: ""

  deployment:
    accessible_namespaces: ["^((?!(istio-operator|kube.*|openshift.*|ibm.*|kiali-operator)).)*$"]
    #additional_service_yaml:
    affinity:
      node: {}
      pod: {}
      pod_anti: {}
    image_name: "kiali/kiali"
    image_pull_policy: "IfNotPresent"
    image_pull_secrets: []
    image_version: "lastrelease"
    ingress_enabled: true
    namespace: "istio-system"
    secret_name: "kiali"
    #service_type: "NodePort"
    tolerations: []
    verbose_mode: "3"
    version_label: ""
    view_only_mode: false

  external_services:
    grafana:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      enabled: true
      in_cluster_url: ""
      url: ""
    istio:
      istio_identity_domain: "svc.cluster.local"
      istio_sidecar_annotation: "sidecar.istio.io/status"
      url_service_version: ""
    prometheus:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      custom_metrics_url: ""
      url: ""
    tracing:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: false
        username: ""
      enabled: true
      namespace: ""
      port: 16686
      service: ""
      url: ""

  identity: {}
    #cert_file:
    #private_key_file:

  istio_labels:
    app_label_name: "app"
    version_label_name: "version"

  kubernetes_config:
    burst: 200
    qps: 175
    cache_enabled: false
    cache_duration: 300000000

  login_token:
    expiration_seconds: 86400
    signing_key: "kiali"

  server:
    address: ""
    audit_log: true
    cors_allow_all: false
    metrics_enabled: true
    metrics_port: 9090
    port: 20001
    web_root: ""

# These variables are outside of the kiali_defaults. Their values will be
# auto-detected by the role and are not meant to be set by the user.
# However, for debugging purposes you can force one of these to true.
is_k8s: false
is_openshift: false
