apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
data:
  config.yaml: |
    istio_namespace: ${ISTIO_NAMESPACE}
    server:
      port: 20001
      web_root: /
    external_services:
      jaeger:
        url: ${JAEGER_URL}
      grafana:
        url: ${GRAFANA_URL}
    auth:
      strategy: ${AUTH_STRATEGY}
      secret: ${OAUTH_SECRET}
    identity:
      cert_file: /kiali-cert/tls.crt
      private_key_file: /kiali-cert/tls.key
