apiVersion: v1
kind: ServiceAccount
metadata:
  name: sws
  labels:
    app: sws
---
apiVersion: v1
kind: Service
metadata:
  name: sws
  labels:
    app: sws
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 20001
  selector:
    app: sws
---
apiVersion: v1
kind: Route
metadata:
  name: sws
  labels:
    app: sws
spec:
  to:
    kind: Service
    name: sws
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sws
  labels:
    app: sws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws
  template:
    metadata:
      name: sws
      labels:
        app: sws
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxAvailable: 1
      type: RollingUpdate
    spec:
      serviceAccount: sws
      containers:
      - image: ${IMAGE_NAME}:${IMAGE_VERSION}
        name: sws
        command:
        - "/opt/sws/sws"
        - "-config"
        - "/sws-configuration/config.yaml"
        - "-v"
        - "${VERBOSE_MODE}"
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: sws-configuration
          mountPath: "/sws-configuration"
      volumes:
      - name: sws-configuration
        configMap:
          name: sws
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: sws
  labels:
    app: sws
rules:
- apiGroups: [""]
  attributeRestrictions: null
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - projects
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups: ["route.openshift.io"]
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
- apiGroups: ["config.istio.io"]
  attributeRestrictions: null
  resources:
  - routerules
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: sws
  labels:
    app: sws
roleRef:
  name: sws
subjects:
- kind: ServiceAccount
  name: sws
  namespace: ${NAMESPACE}
