apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: ${VERSION_LABEL}
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
      web_root: /
    external_services:
      jaeger:
        url: ${JAEGER_URL}
      grafana:
        url: ${GRAFANA_URL}
