name: Prevent committers from approving a PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  preventapprove:
    name: Reject PR approval by committers to the PR
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Dismiss code reviews from collaborators
        uses: peckjon/reject-pr-approval-from-committer@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}